src/menus/urls.py
from django.conf.urls import url

from .views import (
    ItemCreateView,
    ItemDetailView,
    ItemListView,
    ItemUpdateView,
)

urlpatterns = [
    url(r'^$', ItemListView.as_view(), name='list'),
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    # url(r'^(?P<pk>\d+)/update/$', ItemUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
]

src/muypicky/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView

from profiles.views import ProfileFollowToggle

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^u/', include('profiles.urls', namespace='profile')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
]

src/restaurants/urls.py
from django.conf.urls import url

from .views import (
    RestaurantListView,
    RestaurantDetailView,
    RestaurantCreateView,
    RestaurantUpdateView
)

urlpatterns = [
    url(r'^$', RestaurantListView.as_view(), name='list'),
    url(r'^create/$', RestaurantCreateView.as_view(), name='create'),
    # url(r'^(?P<slug>[\w-]+)/edit/$', RestaurantUpdateView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/$', RestaurantUpdateView.as_view(), name='detail'),
]

src/restaurants/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save
from django.core.urlresolvers import reverse

from .utils import unique_slug_generator
from .validators import validate_category

User = settings.AUTH_USER_MODEL


class RestaurantLocationQuerySet(models.query.QuerySet):
    def search(self, query):  # RestaurantLocation.objects.all().search(query)
        if query:
            return self.filter(
                Q(name__icontains=query) |
                Q(location__icontains=query) |
                Q(category__icontains=query) |
                Q(item__name__icontains=query) |
                Q(item__contents__icontains=query)
            ).distinct()
        return self


class RestaurantLocationManager(models.Manager):
    def get_queryset(self):
        return RestaurantLocationQuerySet(self.model, using=self._db)

    def search(self, query):  # RestaurantLocation.objects.search
        return self.get_queryset().search(query)


class RestaurantLocation(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)  # Check out Django Models Unleashed on joincfe.com
    name = models.CharField(max_length=120)
    location = models.CharField(max_length=120, null=True, blank=True)
    category = models.CharField(max_length=120, null=True, blank=True, validators=[validate_category])
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(null=True, blank=True)

    # my_date_field = models.DateField(auto_now=False, auto_now_add=False)

    objects = RestaurantLocationManager()  # Add Model.objects.all()

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('restaurants:detail', kwargs={'slug': self.slug})

    @property
    def title(self):
        return self.name


def rl_pre_save_receiver(sender, instance, *args, **kwargs):
    instance.category = instance.category.capitalize()
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


# def rl_post_save_receiver(sender, instance, *args, **kwargs):
#     print('saved...')
#     print(instance.timestamp)
#     print(instance.updated)
# Never call .save() in post_save signal receiver method as it will be an infinite loop.
# Evertime .save() is called, post_save signal will be called.
# You can do this though if you aren't setting instance slug in pre_save:
# if not instance.slug:
#     instance.slug = unique_slug_generator(instance)
#     instance.save()


pre_save.connect(rl_pre_save_receiver, sender=RestaurantLocation)

# post_save.connect(rl_post_save_receiver, sender=RestaurantLocation)

src/restaurants/forms.py
from django import forms

from .models import RestaurantLocation


class RestaurantCreateForm(forms.Form):
    name = forms.CharField()
    location = forms.CharField(required=False)
    category = forms.CharField(required=False)

    def clean_name(self):
        name = self.cleaned_data.get("name")
        if name == "Hello":
            raise forms.ValidationError("Not a valid name")
        return name


class RestaurantLocationCreateForm(forms.ModelForm):
    # email = forms.EmailField()
    # category = forms.CharField(required=False, validators=[validate_category])

    class Meta:
        model = RestaurantLocation
        fields = [
            'name',
            'location',
            'category',
            'slug',
        ]

    def clean_name(self):
        name = self.cleaned_data.get("name")
        if name == "Hello":
            raise forms.ValidationError("Not a valid name")
        return name

    # def clean_email(self):
    #     email = self.cleaned_data.get('email')
    #     if '.edu' in email:
    #         raise forms.ValidationError("We do not accept edu emails")
    #     return email

src/restaurants/views.py
# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, CreateView, UpdateView
from django.views.generic.list import ListView

from .forms import RestaurantLocationCreateForm
from .models import RestaurantLocation


class RestaurantListView(LoginRequiredMixin, ListView):
    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)


class RestaurantDetailView(LoginRequiredMixin, DetailView):
    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)


class RestaurantCreateView(LoginRequiredMixin, CreateView):
    form_class = RestaurantLocationCreateForm
    # The login_url variable here will override the one that we have set in default settings (base.py)
    login_url = '/login/'  # We are keeping it same for now. But in case someone changes there, it will remain Login
    #  for this view always until we change it here too or remove this variable altogether.
    template_name = 'form.html'

    # success_url = '/restaurants'

    # Overriding form_valid method while implementing class based authentication
    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner = self.request.user
        # instance.save()

        return super(RestaurantCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(RestaurantCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Add Restaurant'
        return context


class RestaurantUpdateView(LoginRequiredMixin, UpdateView):
    form_class = RestaurantLocationCreateForm
    # The login_url variable here will override the one that we have set in default settings (base.py)
    login_url = '/login/'  # We are keeping it same for now. But in case someone changes there, it will remain Login
    #  for this view always until we change it here too or remove this variable altogether.
    template_name = 'restaurants/detail-update.html'

    # success_url = '/restaurants'

    # Overriding form_valid method while implementing class based authentication

    def get_context_data(self, **kwargs):
        context = super(RestaurantUpdateView, self).get_context_data(**kwargs)
        context['title'] = f'Update Restaurant: {self.get_object().name}'
        return context

    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)

src/restaurants/templates/restaurants/detail-update.html
{% extends "base.html" %}

{% block head_title %}{{ form.instance.title }} Restaurants || {{ block.super }} {% endblock head_title %}

{% block content %}
    <h1>{{ form.instance.title }}
        <small>{{ form.instance.category }}</small>
    </h1>
    <p>{{ form.instance.location }}</p>
    <p>Added: {{ form.instance.timestamp }}, Last Updated: {{ form.instance.updated|timesince }} ago</p>

    <hr/>

    <h3>Make Changes</h3>

    {% include 'snippets/form-snippet.html' with form=form  %}


{% endblock content %}

src/restaurants/templates/restaurants/form.html
{% extends "base.html" %}

{% block head_title %}Add Restaurant || {{ block.super }} {% endblock head_title %}

{% block content %}
    <h1>Add Restaurant</h1>

    {% if form.errors.non_field_errors %}
        {{ form.errors.non_field_errors }}
    {% endif %}
    <form method="post"> {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock content %}

{#        <input type="text" name="name" placeholder="Your Title"><br/>#}
{#        <input type="text" name="location" placeholder="Location"><br/>#}
{#        <input type="text" name="category" placeholder="Category"><br/>#}

src/restaurants/templates/restaurants/restaurantlocation_detail.html
{% extends "base.html" %}

{% block head_title %}Restaurant Detail || {{ block.super }} {% endblock head_title %}

{% block content %}
    <h1>{{ object.title }}
        <small>{{ object.category }}</small>
    </h1>
    <p>{{ object.location }}</p>
    <p>Added: {{ object.timestamp }}, Last Updated: {{ object.updated|timesince }} ago</p>
{% endblock content %}

src/restaurants/templates/restaurants/restaurantlocation_list.html
{% extends "base.html" %}

{% block head_title %}Restaurants || {{ block.super }}{% endblock head_title %}

{% block content %}
    <h1>My Restaurants <small><a href="{% url 'restaurants:create' %}">Add</a> </small> </h1>

<ul>
{% for obj in object_list  %}
    <li><a href="{{ obj.get_absolute_url }}">{{ obj }}</a><br/>
        {{ obj.location }} | {{ obj.category }} | {{ obj.timestamp }}</li>
    {% empty %}
    <li><a href="{% url 'restaurants:create' %}">Add a restaurant</a></li>
{% endfor %}

</ul>
{% endblock %}

src/restaurants/templates/restaurants/restaurants_list.html
{% extends "base.html" %}

{% block head_title %}Restaurants || {{ block.super }}{% endblock head_title %}

{% block content %}
    <h1>Restaurants List</h1>

<ul>
{% for obj in object_list  %}
    <li>{{ obj }} | {{ obj.location }} | {{ obj.timestamp }}</li>
{% endfor %}

</ul>
{% endblock %}